pipeline {
  agent any

  stages {
    stage('construcción') {
      agent {
        docker {
          image 'jsf-apps-builder'
          reuseNode true
        }
      }

      steps {
        sh 'mvn -f ProductosApp clean package'
      }
    }

    stage('despliegue') {
      steps {
        sh 'ssh jenkins@172.17.0.3 rm -f ProductosApp.war'
        sh 'scp ProductosApp/target/ProductosApp-1.0-SNAPSHOT.war jenkins@172.17.0.3:/home/jenkins/ProductosApp.war'
        sh 'ssh jenkins@172.17.0.3 sh /opt/payara/appserver/bin/asadmin --user=admin --passwordfile=/opt/payara/passwordFile deploy --force ProductosApp.war'
      }
    }
  }

  post {
    success {
      sh 'echo El proceso de despliegue termino exitosamente'
    }

    failure {
      sh 'echo Hubo un error al momento de desplegar la aplicacion'
    }
  }
}
