#!/bin/sh
user=
userToken=
urlJenkins=
appToken=
crumb=$(wget -q --auth-no-challenge --user $user --password $userToken --output-document - $urlJenkins'/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
curl -X POST --user $user:$userToken -H "$crumb" $urlJenkins/job/ProductosApp/build?token=$appToken
